config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    get 'new_subcategory' => 'categories#new_subcategory'
    resources :discussions do
      resources :messages
    end
  end
  get "/discussions/new/:category_id" => "discussions#new"

  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'all_users' => 'users#list'
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  self.table_name = 'Discussion'

  validates :title, presence: true
  def self.validate?(title, category_id)
    title.length > 3 && (not Category.getCategoryById(category_id).nil?)
  end

  def self.createDiscussion(title, category_id)
    st = ActiveRecord::Base.connection.raw_connection.prepare("INSERT INTO Discussion (title, category_id) VALUES (?, ?)")
    st.execute(title.to_s, category_id.to_i)
    st.close
    #Discussion.find_by_sql(["INSERT INTO Discussion (title, category_id) VALUES (?, ?)", title.to_s, category_id.to_i])
  end

  def self.findDiscussionsByTitle(title)
    Discussion.find_by_sql(["SELECT * FROM Discussion WHERE title LIKE ?", title.to_s])
  end

  def self.getDiscussionById(id)
    Discussion.find_by_sql(["SELECT * FROM Discussion WHERE id=?", id.to_i]).first
  end

  def self.getDiscussionsByCategory(category_id, page=nil)
    offset = 0
    unless page.nil?
      offset = (page.to_i-1) * 10
    end
    Discussion.find_by_sql(["SELECT * FROM Discussion
      JOIN (SELECT discussion_id, MAX(time) AS MostRecent
      FROM Message
      GROUP BY discussion_id) AS M ON Discussion.id = M.discussion_id
      WHERE category_id=?
      ORDER BY M.MostRecent DESC
      LIMIT 10 OFFSET ?", category_id.to_i, offset])
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :list_all_discussions, only: [:index]
  before_action :authenticate_user, only: [:new, :create]
  before_action :set_discussion, only: [:show]
  before_action :set_category, only: [:show, :create]


  def index
  end

  def new
  end

  def create
    if Discussion.validate?(discussion_params[:title], @category.id) && discussion_params[:message] != nil
      Discussion.createDiscussion(discussion_params[:title], @category.id)
      #Dirty hack below.
      discussion = Discussion.where(title: discussion_params[:title]).order("time DESC").first
      Message.createMessage(@current_user.id, discussion_params[:message], discussion.id)
      redirect_to [@category,discussion]
    else
      flash[:alert] = 'Invalid form'
      redirect_to :back
    end
  end

  def show
    @messages = Message.getMessagesByDiscussionId(@discussion.id, params[:page])
  end

  private
  def set_discussion
    @discussion = Discussion.getDiscussionById(params[:id])
  end

  def set_category
    @category = Category.getCategoryById(params[:category_id])
  end

  def list_all_discussions
    @discussions = Discussion.find_by_sql(["SELECT * FROM Discussion"])
  end

  def discussion_params
    # List of common params
    list_params_allowed = [:title, :category_id, :message]
    params.require(:discussion).permit(list_params_allowed)
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
  def get_number_of_discussions_in_category(category_id)
    Discussion.count_by_sql(["SELECT COUNT(*) FROM Discussion WHERE category_id = ?", category_id.to_i])
  end
end

app/views/discussions/new.html.erb
<h1>Create Discussion</h1>
<%= form_for(:discussion, url: {controller: 'discussions', action: 'create'}, html: {class: "form-horizontal"}) do |f| %>
  <div class="form-group">
    <label class="control-laber col-sm-2">Title</label>
    <div class="col-sm-6">
      <%= f.text_field :title, required: true, class: "form-control"%>
    </div>
    <div class="col-sm-4"></div>
  </div>
  <div class="form-group">
    <label class="control-laber col-sm-2">Message</label>
    <div class="col-sm-6">
      <%= f.text_area :message, required: true, rows: 15, class: "form-control"%>
    </div>
    <div class="col-sm-4"></div>
  </div>
  <%= hidden_field_tag :category_id, params[:category_id]%>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create", class: "btn btn-default"%>
    </div>
  </div>
<% end %>
</div>

app/views/discussions/show.html.erb
<%= link_to "Back to discussions", @category %>
<h1><%= @discussion.title %></h1>
<% @messages.each do |message| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">By: <%= link_to User.GetUserById(message.user_id).try(:nick),user_path(message.user_id) %> at <%= TimeSanitizer.output(message.time).try(:strftime, '%d/%m/%Y %H:%M') %></h3>
    </div>
    <div class="panel-body">
      <%= simple_format(h(message.message)) %>
    </div>
  </div>
<% end %>
<% if is_user_logged_in? %>
<%= form_tag category_discussion_messages_path(@category, @discussion) do |f| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Message</h3>
  </div>
  <div class="panel-body">
    <%= text_area_tag 'message', nil, class:'form-control', placeholder:'Write a message', rows:'10' %>
    <br>
     <%= submit_tag "Post Message", class: "btn btn-large btn-primary" %>
  </div>
</div>
<% end %>
<% else %>
Log in to post a message<br/>
<% end %>
<div class="btn-group" style="margin-bottom: 10px" role="group" >
  <% ((get_number_of_messages_in_discussion(@discussion.id)/11) + 1).times do |i| %>
  <%= link_to((i+1), [@category,@discussion, page: (i+1)], class: "btn btn-default")%>
  <% end %>
</div>