config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    get 'new_subcategory' => 'categories#new_subcategory'
    resources :discussions do
      resources :messages
    end
  end
  get "/discussions/new/:category_id" => "discussions#new"

  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'all_users' => 'users#list'
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = 'User'

  def self.Validate?(params)
    User.ValidateNick(params[:nick]) and
    User.ValidatePassword(params[:password], params[:password_confirmation])
  end

  def self.ValidateNick(nick)
    nick.length > 3 and User.GetUserByNick(nick).nil?
  end

  def self.ValidatePassword(password, password_confirmation)
    password.length >= 6 and password == password_confirmation
  end

  def self.CreateUser(nick, password, salt)
    #User.find_by_sql(["INSERT INTO User (nick, password, salt) VALUES (?, ?, ?)", nick.to_s, password, salt])
    st = ActiveRecord::Base.connection.raw_connection.prepare("INSERT INTO User (nick, password, salt) VALUES (?, ?, ?)")
    st.execute(nick.to_s, password, salt)
    st.close
  end

  def self.GetUserByNick(nick)
    User.find_by_sql(["SELECT * FROM User WHERE nick=?", nick.to_s]).first
  end

  def self.GetUserById(id)
    User.find_by_sql(["SELECT * FROM User WHERE id=?", id.to_i]).first
  end

  def self.Authenticate(nick, password)
    user = User.GetUserByNick(nick)
    user and user.password == BCrypt::Engine.hash_secret(password, user.salt)
  end

  def updateNick(nick)
    self.nick = nick.to_s
    st = ActiveRecord::Base.connection.raw_connection.prepare("UPDATE User SET nick=? WHERE id=?")
    st.execute(self.nick, self.id)
    st.close
    #User.find_by_sql(["UPDATE User SET nick=? WHERE id=?", self.nick, self.id])
  end

  def updatePassword(password)
    self.salt = BCrypt::Engine.generate_salt
    self.password = BCrypt::Engine.hash_secret(password, self.salt)
    st = ActiveRecord::Base.connection.raw_connection.prepare("UPDATE User SET password=?, salt=? WHERE id=?")
    st.execute(self.password, self.salt, self.id)
    st.close
    #User.find_by_sql(["UPDATE User SET password=?, salt=? WHERE id=?", self.password, self.salt, self.id])
  end

  def changeAdminStatus(admin)
    self.admin = admin
    st = ActiveRecord::Base.connection.raw_connection.prepare("UPDATE User SET admin=? WHERE id=?")
    st.execute((self.admin ? 1 : 0), self.id)
    st.close
    #User.find_by_sql(["UPDATE User SET admin=? WHERE id=?", (self.admin ? 1 : 0), self.id])
  end

  def newLogin
    time = Time.now.getutc.strftime('%Y-%m-%d %H:%M:%S')
    self.last_login = time
    st = ActiveRecord::Base.connection.raw_connection.prepare("UPDATE User SET last_login=? WHERE id=?")
    st.execute(time, self.id)
    st.close
    #User.find_by_sql(["UPDATE User SET last_login=? WHERE id=?", time, self.id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  unloadable
  require 'bcrypt'
  before_action :set_user, only:[:show, :edit, :update]
  before_action :save_login_state, only: [:new, :create]
  before_action :authenticate_user, only: [:edit, :update]
  before_action :check_if_current_user, only: [:edit, :update]
  before_action :authenticate_admin, only: [:list]

  def new
  end

  def list
    @all_users = User.find_by_sql("SELECT * FROM User")
  end

  def create
    if User.Validate?(user_params)
      password_salt = BCrypt::Engine.generate_salt
      password = BCrypt::Engine.hash_secret(user_params[:password], password_salt)
      User.CreateUser(user_params[:nick], password, password_salt)
      #Whoa, used ActiveRecords find_by here, please don't crucify me. find_by_sql bugged for some reason here 4/5 times
      @user = User.find_by(nick: user_params[:nick])
      session[:user_id] = @user.id
      @user.newLogin
      redirect_to :root, notice: "Successfully logged in!"
    else
      if not User.GetUserByNick(user_params[:nick]).nil?
        flash[:alert] = 'Nick is already taken'
      else
        flash[:alert] = 'Invalid form'
      end
      redirect_to :back
    end
  end

  def edit
  end

  def update
    nick_empty = user_params[:nick].empty?
    password_empty = user_params[:password].empty?
    admin = user_params[:admin] or false
    nick_valid = nick_empty || User.ValidateNick(user_params[:nick])
    password_valid = password_empty || User.ValidatePassword(user_params[:password], user_params[:password_confirmation])
    if nick_valid and password_valid and User.Authenticate(@current_user.nick, user_params[:old_password])
      @user.updateNick(user_params[:nick]) unless nick_empty
      @user.updatePassword(user_params[:password]) unless password_empty
      @user.changeAdminStatus(admin) if @current_user.admin?
      redirect_to @user, notice: "Updated successfully"
    else
      if not nick_valid
        flash[:alert] = 'Nick is already taken or it is too short'
      else
        flash[:alert] = 'Passwords did not match or the current password was wrong'
      end
      redirect_to :back
    end
  end

  def show
  end

  private
  def set_user
    @user = User.GetUserById(params[:id])
  end

  def user_params
    # List of common params
    list_params_allowed = [:nick, :password, :password_confirmation, :old_password]
    # Add the params only for admin
    unless @current_user.nil?
      list_params_allowed << :admin if @current_user.admin?
    end
    params.require(:user).permit(list_params_allowed)
  end

  def check_if_current_user
    if @current_user && (session[:user_id] == params[:id].to_i || @current_user.admin)
      return true
    else
      redirect_to_back_or_root alert: 'You can not change other users'
      return false
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def is_current_user_admin?
    current_user = get_current_user
    if current_user.nil?
      return false
    else
      return current_user.admin
    end
  end

  def is_user_logged_in?
    return session[:user_id] != nil
  end

  def get_current_user
    return User.GetUserById(session[:user_id])
  end
end

app/views/users/edit.html.erb
<div class="Sign_Form">
  <h1>Edit user: <%= @user.nick %></h1>
  <%= form_for(@user) do |f| %>
    <p> New nick:</br> <%= f.text_field :nick, value: nil%> </p>
    
    <p> New password:</br> <%= f.password_field :password%></p>
    <p> Repeat new password:</br> <%= f.password_field :password_confirmation %> </p>
    <% if @current_user.admin %>
      <p> Admin: <%= f.check_box :admin, checked: @user.admin %> </p>
    <% end %>
    <p> Verify new changes with current password:</br> <%= f.password_field :old_password, required: true %> </p>
    <%= f.submit :Update %>
  <% end %>
</div>

app/views/users/list.html.erb
<% @all_users.each do |user| %>
<ul>
<li>
  id: <%= user.id %>
  nick: 
  <%= link_to user.nick, user_path(user) %><br/>
  Admin status: <%= user.admin ? 'True' : 'False'%> | 
  Last login: <%= user.last_login %> | 
  <%= link_to 'Edit', controller: 'users', action: 'edit', id: user.id %>
</li>
</ul>
<% end %>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, url: {controller: 'users', action: 'create'}, html: {class: "form-horizontal"}) do |f| %>
    <div class="form-group">
      <label class="control-laber col-sm-2">Nick:</label>
      <div class="col-sm-6">
        <%= f.text_field :nick, required: true, class: "form-control" %>
      </div>
      <div class="col-sm-4"></div>
    </div>
    <div class="form-group">
      <label class="control-laber col-sm-2">Password:</label>
      <div class="col-sm-6">
        <%= f.password_field :password, required: true, class: "form-control"%>
      </div>
      <div class="col-sm-4"></div>
    </div>
    <div class="form-group">
      <label class="control-laber col-sm-2">Password Confirmation:</label>
      <div class="col-sm-6">
        <%= f.password_field :password_confirmation, required: true, class: "form-control" %>
      </div>
      <div class="col-sm-4"></div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit :Signup, class: "btn btn-success"%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p>Nick:<br/> <%= @user.nick %> </p>
<p><%= link_to 'Edit', edit_user_path(@user) %></p>