config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    get 'new_subcategory' => 'categories#new_subcategory'
    resources :discussions do
      resources :messages
    end
  end
  get "/discussions/new/:category_id" => "discussions#new"

  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'all_users' => 'users#list'
end

app/views/shared/_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times</button>
    <div class="flash-notice"><%= flash[:notice] %></div>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times</button>
    <div class="flash-alert"><%= flash[:alert] %></div>
  </div>
<% end %>

app/views/shared/_login.html.erb
<%= form_tag({controller: "sessions", action: "create"}, {class: 'nav navbar-form'}) do%>
  <div class="form-group">
  <%= text_field_tag :nick, nil, required: true, autocomplete: 'off', placeholder: "Nick", class: 'form-control'%>
  </div>
  <div class="form-group">
  <%= password_field_tag :password, nil, required: true, placeholder: "Password", class: 'form-control'%>
  </div>
  <div class="form-group">
  <%= submit_tag 'Log in', class: 'btn btn-default'%>
  </div>
<% end %>

app/views/shared/_nav_bar.html.erb
<nav class='navbar navbar-inverse navbar-fixed-top'>
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#tikape_navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Tikape-forum</a>
    </div>
  <div class="collapse navbar-collapse" id="tikape_navbar">
    <ul class='nav navbar-nav'>
      <% if is_user_logged_in? %>
        <li class='nav-item'>
          <%= link_to get_current_user.nick, user_path(session[:user_id]),class: 'nav-link'%>
        </li>
        <% if is_current_user_admin? %>
          <li class='nav-item'>
            <%= link_to 'List all users', all_users_path, class: 'nav-link'%>
          </li>
        <% end %>
      <% end %>
      <li class='nav-item'>
        <%= link_to 'Categories', categories_path, class: 'nav-link'%>
      </li>
    </ul>
    <% if not is_user_logged_in? %>
      <div class="nav navbar-right">
      <%= render 'shared/login' %>
      </div>
    <% end %>
    <ul class='nav navbar-nav navbar-right'>
    <% if not is_user_logged_in? %>
      <li class='nav-item'>
        <%= link_to 'Signup', signup_path, class: 'nav-link'%>
      </li>
    <% else %>
      <li class='nav-item'>
        <%= link_to 'Signout', signout_path, class: 'nav-link'%>
      </li>
    <% end %>
    </ul>
    </div>
  </div>
</nav>  