config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories do
    get 'new_subcategory' => 'categories#new_subcategory'
    resources :discussions do
      resources :messages
    end
  end
  get "/discussions/new/:category_id" => "discussions#new"

  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'all_users' => 'users#list'
end

app/models/category.rb
class Category < ApplicationRecord
  self.table_name = 'Category'

  validates :subject, presence: true
  def self.validate?(*args)
    if args.second
      args.first.length > 3 && !Category.getCategoryById(args.second).nil?
    else
      args.first.length > 3
    end
  end

  def self.createCategory(subject)
    st = ActiveRecord::Base.connection.raw_connection.prepare("INSERT INTO Category (subject) VALUES (?)")
    st.execute(subject.to_s)
    st.close
    #Category.find_by_sql(["INSERT INTO Category (subject) VALUES (?)", subject.to_s])
  end

  def self.createSubCategory(subject, category_id)
    st = ActiveRecord::Base.connection.raw_connection.prepare("INSERT INTO Category (subject, upper_category_id) VALUES (?,?)")
    st.execute(subject.to_s, category_id.to_i)
    st.close
    #Category.find_by_sql(["INSERT INTO Category (subject) VALUES (?)", subject.to_s])
  end

  def self.findCategory(subject)
    Category.find_by_sql(["SELECT * FROM Category WHERE subject=?", subject.to_s]).first
  end

  def self.getCategoryById(id)
    Category.find_by_sql(["SELECT * FROM Category WHERE id=?", id.to_i]).first
  end

  def getSubCategories
    Category.find_by_sql(["SELECT * FROM Category WHERE upper_category_id=?", self.id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin, only: [:create, :new, :new_subcategory]
  before_action :set_category, only: [:show]
  before_action :list_all_categories, :list_all_sub_categories, only: [:index, :show]

  def index
  end

  def new
  end

  def create
    if params[:category_id].present?
      if Category.validate?(params[:category][:subject], params[:category_id])
        Category.createSubCategory(params[:category][:subject], params[:category_id])
        category = Category.findCategory(params[:category][:subject])
        #Dirty hack below.
        redirect_to (category)
      else
        flash[:alert] = 'Invalid form'
        redirect_to :back
      end
    else
      if Category.validate?(params[:category][:subject])
        Category.createCategory(params[:category][:subject])
        category = Category.findCategory(params[:category][:subject])
        #Dirty hack below.
        redirect_to (category)
      else
        flash[:alert] = 'Invalid form'
        redirect_to :back
      end
    end
  end

  def new_subcategory
  end

  def show
    if @category.upper_category_id
      @parent_category = Category.getCategoryById(@category.upper_category_id)
    end
    @discussions = Discussion.getDiscussionsByCategory(@category.id, params[:page])
    #.sort_by{|discussion| Message.getMessagesByDiscussionId(discussion.id).map(&:last_edited)}
  end

  private

  def set_category
    @category = Category.getCategoryById(params[:id])
  end

  def list_all_categories
    @categories = Category.find_by_sql(["SELECT * FROM Category WHERE upper_category_id IS NULL"])
  end

  def list_all_sub_categories
    subCategories = Category.find_by_sql(["SELECT * FROM Category WHERE upper_category_id IS NOT NULL"])
    @allSubCategories = {}
    subCategories.each do |subCategory|
      @allSubCategories[subCategory.upper_category_id] ||= Array.new
      @allSubCategories[subCategory.upper_category_id].push(subCategory)
    end
  end

  def category_params
    # List of common params
    list_params_allowed = [:subject, :upper_category_id]
    params.require(:category).permit(list_params_allowed)
  end
end

app/views/categories/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Category</th>
      <th>Discussions</th>
      <th>Messages</th>
      <th>Latest Message</th>
    </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.subject.capitalize, category %></td>
      <td><%= get_number_of_discussions_in_category(category.id) %></td>
      <td><%= get_number_of_messages_in_category(category.id) %></td>
      <td><%= TimeSanitizer.output(get_newest_message_date_in_category(category.id)).try(:strftime, '%d/%m/%Y %H:%M') %></td>
    </tr>
    <% if not @allSubCategories[category.id].nil? %>
      <% @allSubCategories[category.id].each do |subCategory| %>
        <tr>
          <td style="padding-left: 25px">&#8627;<%= link_to subCategory.subject.capitalize, subCategory %></td>
          <td><%= get_number_of_discussions_in_category(subCategory.id) %></td>
          <td><%= get_number_of_messages_in_category(subCategory.id) %></td>
          <td><%= TimeSanitizer.output(get_newest_message_date_in_category(subCategory.id)).try(:strftime, '%d/%m/%Y %H:%M') %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>
<br>
<% if is_current_user_admin? %>
<h2><%= link_to 'Create Category', new_category_path  %></h2>
<% end %>

app/views/categories/new.html.erb
<h1>Create Category</h1>
<%= form_for(:category, url: {controller: 'categories', action: 'create'}, html: {class: "form-horizontal"}) do |f| %>
  <div class="form-group">
    <label class="control-laber col-sm-2">Subject</label>
    <div class="col-sm-6">
      <%= f.text_field :subject, required: true, class: "form-control"%>
    </div>
    <div class="col-sm-4"></div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create", class: "btn btn-default"%>
    </div>
  </div>
<% end %>

app/views/categories/new_subcategory.html.erb
<h1>Create Sub-Category</h1>
<%= form_for(:category, url: {controller: 'categories', action: 'create'}, html: {class: "form-horizontal"}) do |f| %>
  <div class="form-group">
    <label class="control-laber col-sm-2">Subject</label>
    <div class="col-sm-6">
      <%= f.text_field :subject, required: true, class: "form-control"%>
    </div>
    <div class="col-sm-4"></div>
  </div>
  <%= hidden_field_tag :category_id, params[:category_id]%>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create", class: "btn btn-default"%>
    </div>
  </div>
<% end %>

app/views/categories/show.html.erb
<% if @parent_category %>
  <h1><%= link_to @parent_category.subject.capitalize, category_path(@parent_category) %> > <%= @category.subject.capitalize %></h1>
<% else %>
  <h1><%= @category.subject %></h1>
<% end %>
<% if is_user_logged_in? %>
  <%= link_to "Create discussion", new_category_discussion_path(@category) %>
<% else %>
  Login to start a new discussion
<% end %>
<% if is_current_user_admin? %>
  <%= link_to 'Create sub-category', category_new_subcategory_path(@category)  %>
<% end %>
<% if not @allSubCategories[@category.id].nil? %>
  <h3>Sub categories</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Category</th>
        <th>Discussions</th>
        <th>Messages</th>
        <th>Latest Message</th>
      </tr>
    </thead>
    <tbody>
        <% @allSubCategories[@category.id].each do |subCategory| %>
          <tr>
            <td style="padding-left: 25px">&#8627;<%= link_to subCategory.subject, subCategory %></td>
            <td><%= get_number_of_discussions_in_category(subCategory.id) %></td>
            <td><%= get_number_of_messages_in_category(subCategory.id) %></td>
            <td><%= TimeSanitizer.output(get_newest_message_date_in_category(subCategory.id)).try(:strftime, '%d/%m/%Y %H:%M') %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
<% end %>
<h3>Discussions</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Subject</th>
      <th>Messages</th>
      <th>Latest Message</th>
    </tr>
  </thead>
  <tbody>
  <% @discussions.each do |discussion| %>
    <tr>
      <td><%= link_to discussion.title, [@category, discussion] %></td>
      <td><%= get_number_of_messages_in_discussion(discussion.id) %></td>
      <td><%= TimeSanitizer.output(get_newest_message_date_in_discussion(discussion.id)).try(:strftime, '%d/%m/%Y %H:%M') %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<div class="btn-group" style="margin-bottom: 10px" role="group" >
  <% ((get_number_of_discussions_in_category(@category.id)/11) + 1).times do |i| %>
  <%= link_to((i+1), [@category,@discussion, page: (i+1)], class: "btn btn-default")%>
  <% end %>
</div>